### ISSUE TITLE
Add Issue Tracker per PAP

### ISSUE THREAD

**Issue by mlab817** [mlab817/ipms-old#5]
- [ ] create Issue model, migration and controller
- [x] migration table should have the following fields: project_id, title, description, created_by, status (open/close)
- [x] create relationship Project HasMany Issue
- [ ] create IssueComment model, controller, migration
- [x] Issue HasMany Comment

**Comment by mlab817** [comment]
When an issue is completed and there are no other issues open, the PAP is marked validated. 

If a new issue is opened, the PAP becomes unvalidated.
